In [6]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(
    "../Data/Raw/DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [10]:
print("Rows and Columns:", df.shape)

Rows and Columns: (180519, 53)

In [11]:
print("\n Column name:")
print(df.columns.tolist())

 Column name:
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']

In [13]:
print("n\ Data types:")
print(df.dtypes)

n\ Data types:
Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Id                        int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Email                       str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Password                    str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Id                      int64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                        str
Product Name                         str
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object

In [14]:
print("Dataset shape")
print(df.shape)

Dataset shape
(180519, 53)

In [16]:
print("\n Missing Value")
print(df.isnull().sum())

 Missing Value
Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [18]:
print("\n Duplicate Rows")
print(df.duplicated().sum())

 Duplicate Rows
0

In [20]:
print("Unique Order IDs:", df["Order Id"].nunique())
print("Unique Order Item IDs:", df["Order Item Id"].nunique())
print("Unique Customer IDs:", df["Customer Id"].nunique())
print("Unique Product IDs:", df["Product Card Id"])

print("\n Total rows:", len(df))

Unique Order IDs: 65752
Unique Order Item IDs: 180519
Unique Customer IDs: 20652
Unique Product IDs: 0         1360
1         1360
2         1360
3         1360
4         1360
          ...
180514    1004
180515    1004
180516    1004
180517    1004
180518    1004
Name: Product Card Id, Length: 180519, dtype: int64

 Total rows: 180519

In [21]:
print("Unique Product IDs:", df["Product Card Id"].nunique())

Unique Product IDs: 118

In [24]:
print("Order dates:")
print(df["order date (DateOrders)"].head())

print("\n Shipping dates:")
print(df["shipping date (DateOrders)"].head())

Order dates:
0    1/31/2018 22:56
1    1/13/2018 12:27
2    1/13/2018 12:06
3    1/13/2018 11:45
4    1/13/2018 11:24
Name: order date (DateOrders), dtype: str

 Shipping dates:
0     2/3/2018 22:56
1    1/18/2018 12:27
2    1/17/2018 12:06
3    1/16/2018 11:45
4    1/15/2018 11:24
Name: shipping date (DateOrders), dtype: str

In [29]:
df["order date (DateOrders)"] = pd.to_datetime(df["order date (DateOrders)"])
df["shipping date (DateOrders)"] = pd.to_datetime(df["shipping date (DateOrders)"])

print(df["order date (DateOrders)"].dtype)
print(df["shipping date (DateOrders)"].dtype)

datetime64[us]
datetime64[us]

In [34]:
df["Calculated Shipping Days"] = (
    df["shipping date (DateOrders)"]
    - df["order date (DateOrders)"]
).dt.days

df[
    [
        "order date (DateOrders)",
        "shipping date (DateOrders)",
        "Calculated Shipping Days",
        "Days for shipping (real)",
        "Days for shipment (scheduled)"
    ]
].head(10)

,order date (DateOrders),shipping date (DateOrders),Calculated Shipping Days,Days for shipping (real),Days for shipment (scheduled)
0,2018-01-31 22:56:00,2018-02-03 22:56:00,3,3,4
1,2018-01-13 12:27:00,2018-01-18 12:27:00,5,5,4
2,2018-01-13 12:06:00,2018-01-17 12:06:00,4,4,4
3,2018-01-13 11:45:00,2018-01-16 11:45:00,3,3,4
4,2018-01-13 11:24:00,2018-01-15 11:24:00,2,2,4
5,2018-01-13 11:03:00,2018-01-19 11:03:00,6,6,4
6,2018-01-13 10:42:00,2018-01-15 10:42:00,2,2,1
7,2018-01-13 10:21:00,2018-01-15 10:21:00,2,2,1
8,2018-01-13 10:00:00,2018-01-16 10:00:00,3,3,2
9,2018-01-13 09:39:00,2018-01-15 09:39:00,2,2,1

In [35]:
mismatch = (df["Calculated Shipping Days"] != df["Days for shipping (real)"]).sum()
print("Rows where calculated and real shipping days differ:", mismatch)

Rows where calculated and real shipping days differ: 4657

In [37]:
mismatches = df[
    df["Calculated Shipping Days"]
    != df["Days for shipping (real)"]
]

mismatches[
    [
        "order date (DateOrders)",
        "shipping date (DateOrders)",
        "Calculated Shipping Days",
        "Days for shipping (real)",
        "Days for shipment (scheduled)"
    ]
].head(20)

,order date (DateOrders),shipping date (DateOrders),Calculated Shipping Days,Days for shipping (real),Days for shipment (scheduled)
38,2018-01-12 23:30:00,2018-01-13 11:30:00,0,1,0
39,2018-01-12 23:09:00,2018-01-13 11:09:00,0,1,0
40,2018-01-12 22:48:00,2018-01-13 10:48:00,0,1,0
41,2018-01-12 22:27:00,2018-01-13 10:27:00,0,1,0
447,2018-01-11 14:13:00,2018-01-12 02:13:00,0,1,0
448,2018-01-11 13:52:00,2018-01-12 01:52:00,0,1,0
449,2018-01-11 13:31:00,2018-01-12 01:31:00,0,1,0
450,2018-01-11 13:10:00,2018-01-12 01:10:00,0,1,0
451,2018-01-11 12:49:00,2018-01-12 00:49:00,0,1,0
452,2018-01-11 12:28:00,2018-01-12 00:28:00,0,1,0
453,2018-01-11 12:06:00,2018-01-12 00:06:00,0,1,0
1139,2018-01-10 17:11:00,2018-01-11 05:11:00,0,1,0
2572,2017-04-05 12:20:00,2017-04-06 00:20:00,0,1,0
2659,2016-08-02 18:38:00,2016-08-03 06:38:00,0,1,0
2682,2016-06-05 19:03:00,2016-06-06 07:03:00,0,1,0
2724,2016-01-27 12:56:00,2016-01-28 00:56:00,0,1,0
2808,2015-06-22 14:28:00,2015-06-23 02:28:00,0,1,0
2879,2017-04-12 15:39:00,2017-04-13 03:39:00,0,1,0
2881,2017-04-08 23:00:00,2017-04-09 11:00:00,0,1,0
2894,2017-02-09 17:08:00,2017-02-10 05:08:00,0,1,0

In [38]:
df[
    [
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Delivery Status",
        "Late_delivery_risk"
    ]
].head(20)

,Days for shipping (real),Days for shipment (scheduled),Delivery Status,Late_delivery_risk
0,3,4,Advance shipping,0
1,5,4,Late delivery,1
2,4,4,Shipping on time,0
3,3,4,Advance shipping,0
4,2,4,Advance shipping,0
5,6,4,Shipping canceled,0
6,2,1,Late delivery,1
7,2,1,Late delivery,1
8,3,2,Late delivery,1
9,2,1,Late delivery,1
10,6,2,Shipping canceled,0
11,5,2,Late delivery,1
12,4,2,Late delivery,1
13,2,1,Late delivery,1
14,2,1,Late delivery,1
15,2,1,Late delivery,1
16,5,2,Late delivery,1
17,2,1,Late delivery,1
18,2,1,Late delivery,1
19,0,0,Shipping on time,0

In [40]:
df["Delivery Status"].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [41]:
df["Order Id"].value_counts().head(10)

Order Id
45461    5
31115    5
47752    5
17162    5
64813    5
12525    5
5895     5
6783     5
56973    5
5991     5
Name: count, dtype: int64

In [42]:
df[df["Order Id"] == 45461][
    [
        "Order Id",
        "Order Item Id",
        "Product Name",
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Delivery Status"
    ]
]

,Order Id,Order Item Id,Product Name,Days for shipping (real),Days for shipment (scheduled),Delivery Status
49,45461,113598,Under Armour Girls' Toddler Spine Surge Runni,2,2,Shipping on time
515,45461,113596,Nike Men's Dri-FIT Victory Golf Polo,2,2,Shipping on time
112661,45461,113600,O'Brien Men's Neoprene Life Vest,2,2,Shipping on time
179242,45461,113597,Nike Men's CJ Elite 2 TD Football Cleat,2,2,Shipping on time
179305,45461,113599,Nike Men's Free 5.0+ Running Shoe,2,2,Shipping on time

In [44]:
Order_status = (df.groupby("Delivery Status")["Order Id"].nunique().sort_values(ascending=False))
print(Order_status)

Delivery Status
Late delivery        36048
Advance shipping     15127
Shipping on time     11722
Shipping canceled     2855
Name: Order Id, dtype: int64

In [45]:
order_status = (
    df.groupby("Delivery Status")["Order Id"]
      .nunique()
      .sort_values(ascending=False)
)

print(order_status)

Delivery Status
Late delivery        36048
Advance shipping     15127
Shipping on time     11722
Shipping canceled     2855
Name: Order Id, dtype: int64

In [47]:
Order_status_pct = (order_status / df["Order Id"].nunique() * 100).round(2)
print(order_status_pct)

Delivery Status
Late delivery        54.82
Advance shipping     23.01
Shipping on time     17.83
Shipping canceled     4.34
Name: Order Id, dtype: float64

In [49]:
Shipping_mode_orders = (df.groupby("Shipping Mode")["Order Id"].nunique())
print(Shipping_mode_orders)

Shipping Mode
First Class       10079
Same Day           3571
Second Class      12778
Standard Class    39324
Name: Order Id, dtype: int64

In [52]:
shipping_mode_late = (
    df[df["Delivery Status"] == "Late delivery"]
      .groupby("Shipping Mode")["Order Id"]
      .nunique()
)
print(shipping_mode_late)

Shipping Mode
First Class        9602
Same Day           1648
Second Class       9803
Standard Class    14995
Name: Order Id, dtype: int64

In [56]:
shipping_mode_late_rate = (
    shipping_mode_late
    .div(shipping_mode_orders)
    .mul(100)
    .round(2)
)
print(shipping_mode_late_rate.sort_values(ascending=False))

Shipping Mode
First Class       95.27
Second Class      76.72
Same Day          46.15
Standard Class    38.13
Name: Order Id, dtype: float64

In [57]:
market_orders = (
    df.groupby("Market")["Order Id"]
     .nunique()
     .sort_values(ascending=False)
)
print(market_orders)

Market
Europe          18561
Pacific Asia    17577
LATAM           17181
USCA             8579
Africa           3854
Name: Order Id, dtype: int64

In [59]:
market_late = (
    df[df["Delivery Status"] == "Late delivery"]
     .groupby("Market")["Order Id"]
     .nunique()
)

print(market_late)

Market
Africa           2086
Europe          10199
LATAM            9339
Pacific Asia     9720
USCA             4704
Name: Order Id, dtype: int64

In [60]:
market_late_rate = (
    market_late
    .div(market_orders)
    .mul(100)
    .round(2)
)

print(market_late_rate.sort_values(ascending=False))

Market
Pacific Asia    55.30
Europe          54.95
USCA            54.83
LATAM           54.36
Africa          54.13
Name: Order Id, dtype: float64

In [61]:
segment_orders = (
    df.groupby("Customer Segment")["Order Id"]
      .nunique()
)

print(segment_orders)

Customer Segment
Consumer       34119
Corporate      19856
Home Office    11777
Name: Order Id, dtype: int64

In [62]:
segment_late = (
    df[df["Delivery Status"] == "Late delivery"]
      .groupby("Customer Segment")["Order Id"]
      .nunique()
)

print(segment_late)

Customer Segment
Consumer       18672
Corporate      10871
Home Office     6505
Name: Order Id, dtype: int64

In [63]:
segment_late_rate = (
    segment_late
    .div(segment_orders)
    .mul(100)
    .round(2)
)

print(segment_late_rate.sort_values(ascending=False))

Customer Segment
Home Office    55.23
Corporate      54.75
Consumer       54.73
Name: Order Id, dtype: float64

In [64]:
shipping_mode_late_rate = (
    shipping_mode_late
    .div(shipping_mode_orders)
    .mul(100)
    .round(2)
)

print(shipping_mode_late_rate.sort_values(ascending=False))

Shipping Mode
First Class       95.27
Second Class      76.72
Same Day          46.15
Standard Class    38.13
Name: Order Id, dtype: float64

In [65]:
shipping_mode_schedule = (
    df.groupby("Shipping Mode")["Days for shipment (scheduled)"]
      .mean()
      .round(2)
)

print(shipping_mode_schedule)

Shipping Mode
First Class       1.0
Same Day          0.0
Second Class      2.0
Standard Class    4.0
Name: Days for shipment (scheduled), dtype: float64

In [66]:
shipping_mode_actual = (
    df.groupby("Shipping Mode")["Days for shipping (real)"]
      .mean()
      .round(2)
)

print(shipping_mode_actual)

Shipping Mode
First Class       2.00
Same Day          0.48
Second Class      3.99
Standard Class    4.00
Name: Days for shipping (real), dtype: float64

In [67]:
df["Delivery Gap"] = (
    df["Days for shipping (real)"]
    - df["Days for shipment (scheduled)"]
)

df[
    [
        "Shipping Mode",
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Delivery Gap"
    ]
].head(10)

,Shipping Mode,Days for shipping (real),Days for shipment (scheduled),Delivery Gap
0,Standard Class,3,4,-1
1,Standard Class,5,4,1
2,Standard Class,4,4,0
3,Standard Class,3,4,-1
4,Standard Class,2,4,-2
5,Standard Class,6,4,2
6,First Class,2,1,1
7,First Class,2,1,1
8,Second Class,3,2,1
9,First Class,2,1,1

In [68]:
shipping_mode_gap = (
    df.groupby("Shipping Mode")["Delivery Gap"]
      .mean()
      .round(2)
)

print(shipping_mode_gap)

Shipping Mode
First Class       1.00
Same Day          0.48
Second Class      1.99
Standard Class   -0.00
Name: Delivery Gap, dtype: float64

In [73]:
df["Delivery Performance"]= np.where(df["Delivery Gap"] < 0,"Early",np.where(df["Delivery Gap"] == 0,"On Time", "Late"))

In [74]:
df["Delivery Performance"].value_counts()

Delivery Performance
Late       103400
Early       43366
On Time     33753
Name: count, dtype: int64

In [75]:
shipping_performance = pd.crosstab(
    df["Shipping Mode"],
    df["Delivery Performance"],
    normalize="index"
).mul(100).round(2)

print(shipping_performance)

Delivery Performance  Early    Late  On Time
Shipping Mode
First Class            0.00  100.00     0.00
Same Day               0.00   47.83    52.17
Second Class           0.00   79.73    20.27
Standard Class        40.25   39.77    19.99

In [ ]:
order_performance_types = (
    df.groupby("Order Id")["Delivery Performance"]
      .nunique()
)

print(order_performance_types.value_counts())

Delivery Performance
1    65752
Name: count, dtype: int64

In [77]:
order_level = (
    df.groupby("Order Id")
      .agg({
          "Shipping Mode": "first",
          "Delivery Performance": "first"
      })
      .reset_index()
)

order_level.head()

   Order Id   Shipping Mode Delivery Performance
0         1  Standard Class                Early
1         2  Standard Class                Early
2         4  Standard Class                 Late
3         5  Standard Class                 Late
4         7    Second Class                 Late

In [78]:
pd.crosstab(
    order_level["Shipping Mode"],
    order_level["Delivery Performance"],
    normalize="index"
).mul(100).round(2)

Delivery Performance  Early    Late  On Time
Shipping Mode
First Class            0.00  100.00     0.00
Same Day               0.00   48.36    51.64
Second Class           0.00   79.93    20.07
Standard Class        40.15   39.87    19.98

In [79]:
order_level.groupby("Shipping Mode")["Order Id"].nunique()

Shipping Mode
First Class       10079
Same Day           3571
Second Class      12778
Standard Class    39324
Name: Order Id, dtype: int64

In [80]:
df[df["Order Id"] == 45461][
    ["Order Id", "Order Item Id", "Profit Per Order"]
]

KeyError: "['Profit Per Order'] not in index"

In [81]:
[c for c in df.columns if "Profit" in c]

['Order Item Profit Ratio', 'Order Profit Per Order']

In [82]:
df[df["Order Id"] == 45461][
    ["Order Id", "Order Item Id", "Order Profit Per Order"]
]

        Order Id  Order Item Id  Order Profit Per Order
49         45461         113598             -122.730003
515        45461         113596               50.840000
112661     45461         113600              -80.010002
179242     45461         113597               47.770000
179305     45461         113599               16.000000

In [84]:
order_level["Total Profit"] = (
    df.groupby("Order Id")["Order Profit Per Order"]
      .sum()
)

order_level.head()

   Order Id   Shipping Mode Delivery Performance  Total Profit
0         1  Standard Class                Early           NaN
1         2  Standard Class                Early     88.790001
2         4  Standard Class                 Late    195.900002
3         5  Standard Class                 Late           NaN
4         7    Second Class                 Late    124.090000

In [85]:
order_level["Total Profit"].isna().sum()

np.int64(10938)

In [86]:
order_level["Total Profit"].isna().mean() * 100

np.float64(16.635235430100987)

In [87]:
order_level.groupby("Delivery Performance")["Total Profit"].apply(
    lambda x: x.isna().sum()
)

Delivery Performance
Early      2553
Late       6267
On Time    2118
Name: Total Profit, dtype: int64

In [89]:
missing_profit_rate = (
    order_level.groupby("Delivery Performance")["Total Profit"]
    .apply(lambda x: x.isna().mean() * 100)
    .round(2)
)

print(missing_profit_rate)

Delivery Performance
Early      16.17
Late       16.62
On Time    17.27
Name: Total Profit, dtype: float64

In [90]:
profit_by_delivery = (
    order_level.dropna(subset=["Total Profit"])
    .groupby("Delivery Performance")["Total Profit"]
    .mean()
    .round(2)
)

print(profit_by_delivery)

Delivery Performance
Early      61.40
Late       65.03
On Time    63.24
Name: Total Profit, dtype: float64

In [91]:
order_market = (
    df.groupby("Order Id")["Market"]
      .first()
      .reset_index()
)

order_market.head()

   Order Id Market
0         1  LATAM
1         2  LATAM
2         4  LATAM
3         5  LATAM
4         7  LATAM

In [92]:
order_market_types = (
    df.groupby("Order Id")["Market"]
      .nunique()
)

order_market_types.value_counts()

Market
1    65752
Name: count, dtype: int64

In [93]:
order_level = order_level.merge(
    order_market,
    on="Order Id",
    how="left"
)

order_level.head()

   Order Id   Shipping Mode Delivery Performance  Total Profit Market
0         1  Standard Class                Early           NaN  LATAM
1         2  Standard Class                Early     88.790001  LATAM
2         4  Standard Class                 Late    195.900002  LATAM
3         5  Standard Class                 Late           NaN  LATAM
4         7    Second Class                 Late    124.090000  LATAM

In [94]:
first_class = order_level[
    order_level["Shipping Mode"] == "First Class"
]

first_class["Market"].value_counts()

Market
Europe          2878
Pacific Asia    2668
LATAM           2638
USCA            1338
Africa           557
Name: count, dtype: int64

In [95]:
late_rate_market_shipping = (
    pd.crosstab(
        [order_level["Market"], order_level["Shipping Mode"]],
        order_level["Delivery Performance"],
        normalize="index"
    )["Late"]
    .mul(100)
    .round(2)
)

late_rate_market_shipping

Market        Shipping Mode
Africa        First Class       100.00
              Same Day           48.29
              Second Class       80.14
              Standard Class     39.99
Europe        First Class       100.00
              Same Day           48.05
              Second Class       79.97
              Standard Class     39.88
LATAM         First Class       100.00
              Same Day           51.48
              Second Class       79.35
              Standard Class     39.45
Pacific Asia  First Class       100.00
              Same Day           47.55
              Second Class       80.40
              Standard Class     40.25
USCA          First Class       100.00
              Same Day           44.64
              Second Class       79.92
              Standard Class     39.87
Name: Late, dtype: float64

In [96]:
order_shipping_days = (
    df.groupby("Shipping Mode")[
        ["Days for shipping (real)", "Days for shipment (scheduled)"]
    ]
    .mean()
    .round(2)
)

order_shipping_days

                Days for shipping (real)  Days for shipment (scheduled)
Shipping Mode
First Class                         2.00                            1.0
Same Day                            0.48                            0.0
Second Class                        3.99                            2.0
Standard Class                      4.00                            4.0

In [97]:
df["Order Month"] = df["order date (DateOrders)"].dt.to_period("M")

In [98]:
first_class_monthly = (
    df[df["Shipping Mode"] == "First Class"]
    .groupby("Order Month")[
        ["Days for shipping (real)", "Days for shipment (scheduled)"]
    ]
    .mean()
    .round(2)
)

first_class_monthly

             Days for shipping (real)  Days for shipment (scheduled)
Order Month
2015-01                           2.0                            1.0
2015-02                           2.0                            1.0
2015-03                           2.0                            1.0
2015-04                           2.0                            1.0
2015-05                           2.0                            1.0
2015-06                           2.0                            1.0
2015-07                           2.0                            1.0
2015-08                           2.0                            1.0
2015-09                           2.0                            1.0
2015-10                           2.0                            1.0
2015-11                           2.0                            1.0
2015-12                           2.0                            1.0
2016-01                           2.0                            1.0
2016-02                           2.0                            1.0
2016-03                           2.0                            1.0
2016-04                           2.0                            1.0
2016-05                           2.0                            1.0
2016-06                           2.0                            1.0
2016-07                           2.0                            1.0
2016-08                           2.0                            1.0
2016-09                           2.0                            1.0
2016-10                           2.0                            1.0
2016-11                           2.0                            1.0
2016-12                           2.0                            1.0
2017-01                           2.0                            1.0
2017-02                           2.0                            1.0
2017-03                           2.0                            1.0
2017-04                           2.0                            1.0
2017-05                           2.0                            1.0
2017-06                           2.0                            1.0
2017-07                           2.0                            1.0
2017-08                           2.0                            1.0
2017-09                           2.0                            1.0
2017-10                           2.0                            1.0
2017-11                           2.0                            1.0
2017-12                           2.0                            1.0
2018-01                           2.0                            1.0

In [100]:
df[df["Shipping Mode"] == "First Class"][
    "Days for shipping (real)"
].value_counts().sort_index()

Days for shipping (real)
2    27814
Name: count, dtype: int64

In [101]:
first_class_department = (
    df[df["Shipping Mode"] == "First Class"]
    .groupby("Department Name")
    .size()
    .sort_values(ascending=False)
)

first_class_department

Department Name
Fan Shop              10249
Apparel                7433
Golf                   5276
Footwear               2252
Outdoors               1458
Fitness                 397
Discs Shop              276
Technology              269
Pet Shop                 84
Health and Beauty        67
Book Shop                53
dtype: int64

In [102]:
order_department = (
    df.groupby("Order Id")["Department Name"]
      .first()
      .reset_index()
)

order_department.head()

   Order Id Department Name
0         1        Fan Shop
1         2        Fan Shop
2         4        Outdoors
3         5         Apparel
4         7        Fan Shop

In [103]:
order_department_check = (
    df.groupby("Order Id")["Department Name"]
      .nunique()
)

order_department_check.value_counts()

Department Name
1    24281
2    21318
3    16066
4     3906
5      181
Name: count, dtype: int64

In [104]:
order_department = (
    df.groupby("Order Id")["Department Name"]
      .first()
      .reset_index()
)

In [105]:
department_shipping = pd.crosstab(
    df["Department Name"],
    df["Shipping Mode"],
    normalize="index"
).mul(100).round(2)

department_shipping

Shipping Mode       First Class  Same Day  Second Class  Standard Class
Department Name
Apparel                   15.17      5.42         19.77           59.65
Book Shop                 13.09     10.86         15.80           60.25
Discs Shop                13.62      5.08         18.76           62.54
Fan Shop                  15.33      5.41         19.46           59.80
Fitness                   16.01      5.32         19.28           59.38
Footwear                  15.50      5.39         19.37           59.73
Golf                      15.88      5.35         19.34           59.43
Health and Beauty         18.51      3.87         18.23           59.39
Outdoors                  15.05      5.19         19.47           60.28
Pet Shop                  17.07      8.13         24.19           50.61
Technology                18.36      4.85         19.59           57.20

In [106]:
df["Order Day"] = df["order date (DateOrders)"].dt.day_name()

In [107]:
first_class_day = (
    df[df["Shipping Mode"] == "First Class"]
    .groupby("Order Day")[
        ["Days for shipping (real)", "Days for shipment (scheduled)"]
    ]
    .mean()
    .round(2)
)

first_class_day

           Days for shipping (real)  Days for shipment (scheduled)
Order Day
Friday                          2.0                            1.0
Monday                          2.0                            1.0
Saturday                        2.0                            1.0
Sunday                          2.0                            1.0
Thursday                        2.0                            1.0
Tuesday                         2.0                            1.0
Wednesday                       2.0                            1.0

In [108]:
shipping_mode_performance = (
    df.groupby("Shipping Mode")[
        ["Days for shipping (real)", "Days for shipment (scheduled)"]
    ]
    .mean()
    .round(2)
)

shipping_mode_performance

                Days for shipping (real)  Days for shipment (scheduled)
Shipping Mode
First Class                         2.00                            1.0
Same Day                            0.48                            0.0
Second Class                        3.99                            2.0
Standard Class                      4.00                            4.0

In [109]:
shipping_time_distribution = (
    df.groupby("Shipping Mode")["Days for shipping (real)"]
      .value_counts()
      .sort_index()
)

shipping_time_distribution

Shipping Mode   Days for shipping (real)
First Class     2                           27814
Same Day        0                            5080
                1                            4657
Second Class    2                            7138
                3                            7065
                4                            6978
                5                            7052
                6                            6983
Standard Class  2                           21666
                3                           21700
                4                           21535
                5                           21111
                6                           21740
Name: count, dtype: int64

In [110]:
df[df["Shipping Mode"] == "First Class"][
    "Days for shipment (scheduled)"
].value_counts().sort_index()

Days for shipment (scheduled)
1    27814
Name: count, dtype: int64

In [111]:
first_class_orders = (
    order_level[
        order_level["Shipping Mode"] == "First Class"
    ]["Order Id"].nunique()
)

total_orders = order_level["Order Id"].nunique()

print("First Class Orders:", first_class_orders)
print("Total Orders:", total_orders)
print(
    "First Class Share:",
    round(first_class_orders / total_orders * 100, 2),
    "%"
)

First Class Orders: 10079
Total Orders: 65752
First Class Share: 15.33 %

The stronger finding is:

First Class has a systematic scheduling mismatch: 15.33% of orders are assigned a 1-day delivery target, while the recorded actual shipping time is consistently 2 days.

In [112]:
df["Category Name"].nunique()

50

In [113]:
df["Category Name"].value_counts().head(15)

Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Name: count, dtype: int64

In [114]:
category_late_rate = (
    pd.crosstab(
        df["Category Name"],
        df["Delivery Performance"],
        normalize="index"
    )["Late"]
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

category_late_rate

Category Name
Golf Bags & Carts       68.85
Lacrosse                62.10
Cameras                 61.99
Pet Supplies            61.38
Sporting Goods          59.94
Basketball              59.70
Fitness Accessories     59.55
Crafts                  59.50
Strength Training       59.46
Music                   59.45
Boxing & MMA            59.34
Consumer Electronics    59.16
Accessories             59.16
As Seen on  TV!         58.82
Girls' Apparel          58.62
Women's Clothing        58.62
Health and Beauty       58.56
Electronics             58.52
Trade-In                58.42
Hunting & Shooting      58.41
Golf Gloves             58.41
Toys                    58.41
Kids' Golf Clubs        58.33
Tennis & Racquet        57.93
Golf Shoes              57.82
Shop By Sport           57.61
Books                   57.53
Golf Balls              57.42
Cleats                  57.33
Fishing                 57.32
Indoor/Outdoor Games    57.22
Water Sports            57.21
Women's Apparel         57.13
Garden                  57.02
Cardio Equipment        56.94
Men's Footwear          56.93
Women's Golf Clubs      56.91
Camping & Hiking        56.90
Men's Clothing          56.73
Children's Clothing     56.60
Baseball & Softball     56.49
Video Games             56.32
DVDs                    56.31
Soccer                  55.80
Hockey                  55.70
Baby                    54.59
CDs                     54.24
Golf Apparel            53.29
Computers               52.71
Men's Golf Clubs        49.82
Name: Late, dtype: float64

In [115]:
category_analysis = (
    df.groupby("Category Name")
      .agg(
          Order_Items=("Order Item Id", "nunique"),
          Late_Rate=("Delivery Performance", lambda x: (x == "Late").mean() * 100)
      )
      .sort_values("Late_Rate", ascending=False)
      .round(2)
)

category_analysis

                      Order_Items  Late_Rate
Category Name
Golf Bags & Carts              61      68.85
Lacrosse                      343      62.10
Cameras                       592      61.99
Pet Supplies                  492      61.38
Sporting Goods                357      59.94
Basketball                     67      59.70
Fitness Accessories           309      59.55
Crafts                        484      59.50
Strength Training             111      59.46
Music                         434      59.45
Boxing & MMA                  423      59.34
Consumer Electronics          431      59.16
Accessories                  1780      59.16
As Seen on  TV!                68      58.82
Girls' Apparel               1201      58.62
Women's Clothing              650      58.62
Health and Beauty             362      58.56
Electronics                  3156      58.52
Trade-In                      974      58.42
Toys                          529      58.41
Golf Gloves                  1070      58.41
Hunting & Shooting            440      58.41
Kids' Golf Clubs              384      58.33
Tennis & Racquet              328      57.93
Golf Shoes                    524      57.82
Shop By Sport               10984      57.61
Books                         405      57.53
Golf Balls                   1475      57.42
Cleats                      24551      57.33
Fishing                     17325      57.32
Indoor/Outdoor Games        19298      57.22
Water Sports                15540      57.21
Women's Apparel             21035      57.13
Garden                        484      57.02
Cardio Equipment            12487      56.94
Men's Footwear              22246      56.93
Women's Golf Clubs            181      56.91
Camping & Hiking            13729      56.90
Men's Clothing                208      56.73
Children's Clothing           652      56.60
Baseball & Softball           632      56.49
Video Games                   838      56.32
DVDs                          483      56.31
Soccer                        138      55.80
Hockey                        614      55.70
Baby                          207      54.59
CDs                           271      54.24
Golf Apparel                  441      53.29
Computers                     442      52.71
Men's Golf Clubs              283      49.82

Finding:

Late delivery is broadly distributed across major product categories, with high-volume categories showing late rates around 57%; no major category stands out as a clear delivery-performance driver.

In [116]:
category_profit = (
    df.dropna(subset=["Order Profit Per Order"])
      .groupby("Category Name")
      .agg(
          Total_Profit=("Order Profit Per Order", "sum"),
          Order_Items=("Order Item Id", "nunique")
      )
      .sort_values("Total_Profit", ascending=False)
      .round(2)
)

category_profit

                      Total_Profit  Order_Items
Category Name
Fishing                  756220.77        17325
Cleats                   494636.92        24551
Camping & Hiking         427455.57        13729
Cardio Equipment         383011.10        12487
Women's Apparel          350421.03        21035
Water Sports             325146.96        15540
Indoor/Outdoor Games     318451.43        19298
Men's Footwear           311902.82        22246
Shop By Sport            129813.96        10984
Computers                 69656.81          442
Electronics               40891.38         3156
Garden                    33443.01          484
Cameras                   30289.80          592
Children's Clothing       27178.10          652
Crafts                    25531.17          484
Women's Clothing          19102.85          650
Girls' Apparel            17288.57         1201
Accessories               16643.52         1780
Music                     14436.32          434
Consumer Electronics      13223.40          431
Golf Gloves               12975.49         1070
Baseball & Softball       12762.13          632
Sporting Goods            12518.61          357
Golf Shoes                12406.07          524
Health and Beauty          9493.63          362
Kids' Golf Clubs           9045.84          384
Boxing & MMA               8641.37          423
Golf Balls                 8342.67         1475
Trade-In                   7915.37          974
DVDs                       6655.43          483
Hunting & Shooting         5980.00          440
Tennis & Racquet           5747.98          328
Men's Golf Clubs           5517.99          283
Hockey                     5397.43          614
Fitness Accessories        5258.39          309
Women's Golf Clubs         5028.64          181
Lacrosse                   4364.29          343
Soccer                     3901.95          138
Pet Supplies               3589.26          492
Golf Apparel               3496.31          441
Video Games                2717.52          838
Men's Clothing             2006.04          208
Basketball                 1845.67           67
Golf Bags & Carts          1810.07           61
Baby                       1525.03          207
Toys                        900.71          529
Books                       883.01          405
As Seen on  TV!             714.43           68
CDs                         383.85          271
Strength Training           332.31          111

In [117]:
category_profit["Avg_Profit_Per_Item"] = (
    category_profit["Total_Profit"] /
    category_profit["Order_Items"]
).round(2)

category_profit.sort_values(
    "Avg_Profit_Per_Item",
    ascending=False
)

                      Total_Profit  Order_Items  Avg_Profit_Per_Item
Category Name
Computers                 69656.81          442               157.59
Garden                    33443.01          484                69.10
Crafts                    25531.17          484                52.75
Cameras                   30289.80          592                51.17
Fishing                  756220.77        17325                43.65
Children's Clothing       27178.10          652                41.68
Sporting Goods            12518.61          357                35.07
Music                     14436.32          434                33.26
Camping & Hiking         427455.57        13729                31.14
Consumer Electronics      13223.40          431                30.68
Cardio Equipment         383011.10        12487                30.67
Golf Bags & Carts          1810.07           61                29.67
Women's Clothing          19102.85          650                29.39
Soccer                     3901.95          138                28.28
Women's Golf Clubs         5028.64          181                27.78
Basketball                 1845.67           67                27.55
Health and Beauty          9493.63          362                26.23
Golf Shoes                12406.07          524                23.68
Kids' Golf Clubs           9045.84          384                23.56
Water Sports             325146.96        15540                20.92
Boxing & MMA               8641.37          423                20.43
Baseball & Softball       12762.13          632                20.19
Cleats                   494636.92        24551                20.15
Men's Golf Clubs           5517.99          283                19.50
Tennis & Racquet           5747.98          328                17.52
Fitness Accessories        5258.39          309                17.02
Women's Apparel          350421.03        21035                16.66
Indoor/Outdoor Games     318451.43        19298                16.50
Girls' Apparel            17288.57         1201                14.40
Men's Footwear           311902.82        22246                14.02
DVDs                       6655.43          483                13.78
Hunting & Shooting         5980.00          440                13.59
Electronics               40891.38         3156                12.96
Lacrosse                   4364.29          343                12.72
Golf Gloves               12975.49         1070                12.13
Shop By Sport            129813.96        10984                11.82
As Seen on  TV!             714.43           68                10.51
Men's Clothing             2006.04          208                 9.64
Accessories               16643.52         1780                 9.35
Hockey                     5397.43          614                 8.79
Trade-In                   7915.37          974                 8.13
Golf Apparel               3496.31          441                 7.93
Baby                       1525.03          207                 7.37
Pet Supplies               3589.26          492                 7.30
Golf Balls                 8342.67         1475                 5.66
Video Games                2717.52          838                 3.24
Strength Training           332.31          111                 2.99
Books                       883.01          405                 2.18
Toys                        900.71          529                 1.70
CDs                         383.85          271                 1.42

In [118]:
category_profitability = (
    df.dropna(subset=["Order Profit Per Order"])
      .groupby("Category Name")
      .agg(
          Total_Sales=("Sales", "sum"),
          Total_Profit=("Order Profit Per Order", "sum"),
          Order_Items=("Order Item Id", "nunique")
      )
)

category_profitability["Profit_Margin_%"] = (
    category_profitability["Total_Profit"]
    / category_profitability["Total_Sales"]
    * 100
).round(2)

category_profitability = category_profitability.sort_values(
    "Total_Profit",
    ascending=False
)

category_profitability

,Total_Sales,Total_Profit,Order_Items,Profit_Margin_%
Category Name,,,,
Fishing,6.929654e+06,756220.767190,17325,10.91
Cleats,4.431943e+06,494636.919791,24551,11.16
Camping & Hiking,4.118426e+06,427455.568106,13729,10.38
Cardio Equipment,3.694843e+06,383011.098485,12487,10.37
Women's Apparel,3.147800e+06,350421.029567,21035,11.13
Water Sports,3.113845e+06,325146.960038,15540,10.44
Indoor/Outdoor Games,2.888994e+06,318451.430554,19298,11.02
Men's Footwear,2.891758e+06,311902.820214,22246,10.79
Shop By Sport,1.309522e+06,129813.960315,10984,9.91
Computers,6.630000e+05,69656.810171,442,10.51
Electronics,3.710346e+05,40891.379918,3156,11.02
Garden,2.577687e+05,33443.010106,484,12.97
Cameras,2.676077e+05,30289.799946,592,11.32
Children's Clothing,2.328292e+05,27178.099597,652,11.67
Crafts,2.233563e+05,25531.170060,484,11.43
Women's Clothing,1.402830e+05,19102.849930,650,13.62
Girls' Apparel,1.517062e+05,17288.569973,1201,11.40
Accessories,1.336715e+05,16643.520074,1780,12.45
Music,1.131221e+05,14436.319923,434,12.76
Consumer Electronics,1.089913e+05,13223.399926,431,12.13
Golf Gloves,1.166954e+05,12975.490078,1070,11.12
Baseball & Softball,9.405715e+04,12762.130067,632,13.57
Sporting Goods,1.170068e+05,12518.610119,357,10.70
Golf Shoes,1.079980e+05,12406.070143,524,11.49
Health and Beauty,1.060805e+05,9493.629974,362,8.95
Kids' Golf Clubs,9.879758e+04,9045.839896,384,9.16
Boxing & MMA,8.520541e+04,8641.370006,423,10.14
Golf Balls,7.709816e+04,8342.670024,1475,10.82
Trade-In,6.872178e+04,7915.369985,974,11.52
DVDs,7.939554e+04,6655.430088,483,8.38
Hunting & Shooting,5.684842e+04,5979.999945,440,10.52
Tennis & Racquet,4.458509e+04,5747.979996,328,12.89
Men's Golf Clubs,4.703580e+04,5517.989977,283,11.73
Hockey,4.836073e+04,5397.430013,614,11.16
Fitness Accessories,3.560144e+04,5258.390016,309,14.77
Women's Golf Clubs,4.454597e+04,5028.639929,181,11.29
Lacrosse,3.946479e+04,4364.289984,343,11.06
Soccer,2.647705e+04,3901.949953,138,14.74
Pet Supplies,4.152480e+04,3589.259959,492,8.64
Golf Apparel,3.496975e+04,3496.309983,441,10.00
Video Games,3.331050e+04,2717.519997,838,8.16
Men's Clothing,4.385680e+04,2006.039969,208,4.57
Basketball,2.709933e+04,1845.670003,67,6.81
Golf Bags & Carts,1.036939e+04,1810.069992,61,17.46
Baby,1.222956e+04,1525.029992,207,12.47
Toys,6.104660e+03,900.710000,529,14.75
Books,1.258740e+04,883.010008,405,7.02
As Seen on TV!,2.059794e+04,714.429980,68,3.47
CDs,3.059590e+03,383.850000,271,12.55
Strength Training,5.489553e+04,332.310091,111,0.61

In [119]:
sales_median = category_profitability["Total_Sales"].median()
margin_median = category_profitability["Profit_Margin_%"].median()

high_sales_low_margin = category_profitability[
    (category_profitability["Total_Sales"] >= sales_median) &
    (category_profitability["Profit_Margin_%"] < margin_median)
].sort_values("Total_Sales", ascending=False)

high_sales_low_margin

,Total_Sales,Total_Profit,Order_Items,Profit_Margin_%
Category Name,,,,
Fishing,6.929654e+06,756220.767190,17325,10.91
Camping & Hiking,4.118426e+06,427455.568106,13729,10.38
Cardio Equipment,3.694843e+06,383011.098485,12487,10.37
Water Sports,3.113845e+06,325146.960038,15540,10.44
Men's Footwear,2.891758e+06,311902.820214,22246,10.79
Indoor/Outdoor Games,2.888994e+06,318451.430554,19298,11.02
Shop By Sport,1.309522e+06,129813.960315,10984,9.91
Computers,6.630000e+05,69656.810171,442,10.51
Electronics,3.710346e+05,40891.379918,3156,11.02
Sporting Goods,1.170068e+05,12518.610119,357,10.70
Health and Beauty,1.060805e+05,9493.629974,362,8.95
Kids' Golf Clubs,9.879758e+04,9045.839896,384,9.16

In [120]:
df["Order Item Discount Rate"].describe()

count    180519.000000
mean          0.101668
std           0.070415
min           0.000000
25%           0.040000
50%           0.100000
75%           0.160000
max           0.250000
Name: Order Item Discount Rate, dtype: float64

In [121]:
category_discount = (
    df.groupby("Category Name")
      .agg(
          Avg_Discount_Rate=("Order Item Discount Rate", "mean")
      )
)

category_discount["Avg_Discount_%"] = (
    category_discount["Avg_Discount_Rate"] * 100
).round(2)

category_discount = category_discount.drop(
    columns="Avg_Discount_Rate"
)

category_discount.sort_values(
    "Avg_Discount_%",
    ascending=False
)

                      Avg_Discount_%
Category Name
As Seen on  TV!                10.94
Golf Shoes                     10.56
Strength Training              10.50
Hunting & Shooting             10.47
Baby                           10.43
Accessories                    10.38
Boxing & MMA                   10.37
Baseball & Softball            10.29
Men's Clothing                 10.27
Fitness Accessories            10.26
Sporting Goods                 10.24
Trade-In                       10.24
Lacrosse                       10.23
Books                          10.23
Golf Gloves                    10.23
Tennis & Racquet               10.23
Computers                      10.22
Video Games                    10.21
DVDs                           10.20
Women's Clothing               10.20
Girls' Apparel                 10.19
Electronics                    10.18
Women's Apparel                10.17
Cardio Equipment               10.17
Consumer Electronics           10.17
Crafts                         10.17
Camping & Hiking               10.17
Water Sports                   10.17
Women's Golf Clubs             10.17
Fishing                        10.17
Toys                           10.17
Men's Footwear                 10.17
Cameras                        10.16
Cleats                         10.16
Pet Supplies                   10.16
Indoor/Outdoor Games           10.15
CDs                            10.15
Children's Clothing            10.15
Health and Beauty              10.14
Music                          10.14
Shop By Sport                  10.14
Garden                         10.12
Golf Balls                     10.10
Hockey                         10.06
Golf Apparel                   10.00
Men's Golf Clubs                9.91
Basketball                      9.90
Kids' Golf Clubs                9.67
Soccer                          9.61
Golf Bags & Carts               9.34

That's a valuable finding:

Discounting does not appear to be the main differentiator behind the lower margins of high-sales categories, because their average discount rates are very similar to the overall dataset average (~10.17%).

In [122]:
df[[
    "Product Price",
    "Order Profit Per Order",
    "Order Item Profit Ratio"
]].describe()

       Product Price  Order Profit Per Order  Order Item Profit Ratio
count  180519.000000           180519.000000            180519.000000
mean      141.232550               21.974989                 0.120647
std       139.732492              104.433526                 0.466796
min         9.990000            -4274.979980                -2.750000
25%        50.000000                7.000000                 0.080000
50%        59.990002               31.520000                 0.270000
75%       199.990005               64.800003                 0.360000
max      1999.989990              911.799988                 0.500000

In [123]:
category_profit_ratio = (
    df.groupby("Category Name")
      .agg(
          Avg_Profit_Ratio=("Order Item Profit Ratio", "mean")
      )
)

category_profit_ratio["Avg_Profit_Ratio_%"] = (
    category_profit_ratio["Avg_Profit_Ratio"] * 100
).round(2)

category_profit_ratio = category_profit_ratio.drop(
    columns="Avg_Profit_Ratio"
)

category_profit_ratio.sort_values(
    "Avg_Profit_Ratio_%",
    ascending=True
)

                      Avg_Profit_Ratio_%
Category Name
Men's Clothing                      5.30
Strength Training                   5.95
As Seen on  TV!                     6.49
Books                               7.91
Video Games                         9.17
Hunting & Shooting                  9.29
Pet Supplies                        9.41
Health and Beauty                   9.56
DVDs                                9.65
Golf Apparel                       10.00
Kids' Golf Clubs                   10.56
Basketball                         10.81
Shop By Sport                      11.22
Boxing & MMA                       11.26
Camping & Hiking                   11.59
Water Sports                       11.65
Computers                          11.71
Golf Balls                         11.82
Girls' Apparel                     11.86
Cardio Equipment                   11.88
Men's Footwear                     12.01
Sporting Goods                     12.11
Golf Shoes                         12.13
Fishing                            12.14
Women's Apparel                    12.22
Indoor/Outdoor Games               12.39
Electronics                        12.46
Cleats                             12.46
Crafts                             12.54
Cameras                            12.65
Trade-In                           12.68
Golf Gloves                        12.79
Hockey                             12.80
Children's Clothing                12.97
Lacrosse                           13.14
Accessories                        13.24
Tennis & Racquet                   13.36
Consumer Electronics               13.39
CDs                                13.59
Baseball & Softball                13.80
Baby                               13.94
Garden                             14.25
Music                              14.26
Men's Golf Clubs                   14.56
Women's Golf Clubs                 14.56
Soccer                             14.65
Women's Clothing                   15.10
Fitness Accessories                15.12
Toys                               16.19
Golf Bags & Carts                  19.15

In [124]:
weighted_profit_ratio = (
    df.groupby("Category Name")
      .agg(
          Total_Sales=("Sales", "sum"),
          Total_Profit=("Order Profit Per Order", "sum")
      )
)

weighted_profit_ratio["Weighted_Profit_Ratio_%"] = (
    weighted_profit_ratio["Total_Profit"]
    / weighted_profit_ratio["Total_Sales"]
    * 100
).round(2)

weighted_profit_ratio.sort_values(
    "Weighted_Profit_Ratio_%",
    ascending=True
)

                       Total_Sales   Total_Profit  Weighted_Profit_Ratio_%
Category Name
Strength Training     5.489553e+04     332.310091                     0.61
As Seen on  TV!       2.059794e+04     714.429980                     3.47
Men's Clothing        4.385680e+04    2006.039969                     4.57
Basketball            2.709933e+04    1845.670003                     6.81
Books                 1.258740e+04     883.010008                     7.02
Video Games           3.331050e+04    2717.519997                     8.16
DVDs                  7.939554e+04    6655.430088                     8.38
Pet Supplies          4.152480e+04    3589.259959                     8.64
Health and Beauty     1.060805e+05    9493.629974                     8.95
Kids' Golf Clubs      9.879758e+04    9045.839896                     9.16
Shop By Sport         1.309522e+06  129813.960315                     9.91
Golf Apparel          3.496975e+04    3496.309983                    10.00
Boxing & MMA          8.520541e+04    8641.370006                    10.14
Cardio Equipment      3.694843e+06  383011.098485                    10.37
Camping & Hiking      4.118426e+06  427455.568106                    10.38
Water Sports          3.113845e+06  325146.960038                    10.44
Computers             6.630000e+05   69656.810171                    10.51
Hunting & Shooting    5.684842e+04    5979.999945                    10.52
Sporting Goods        1.170068e+05   12518.610119                    10.70
Men's Footwear        2.891758e+06  311902.820214                    10.79
Golf Balls            7.709816e+04    8342.670024                    10.82
Fishing               6.929654e+06  756220.767190                    10.91
Electronics           3.710346e+05   40891.379918                    11.02
Indoor/Outdoor Games  2.888994e+06  318451.430554                    11.02
Lacrosse              3.946479e+04    4364.289984                    11.06
Golf Gloves           1.166954e+05   12975.490078                    11.12
Women's Apparel       3.147800e+06  350421.029567                    11.13
Cleats                4.431943e+06  494636.919791                    11.16
Hockey                4.836073e+04    5397.430013                    11.16
Women's Golf Clubs    4.454597e+04    5028.639929                    11.29
Cameras               2.676077e+05   30289.799946                    11.32
Girls' Apparel        1.517062e+05   17288.569973                    11.40
Crafts                2.233563e+05   25531.170060                    11.43
Golf Shoes            1.079980e+05   12406.070143                    11.49
Trade-In              6.872178e+04    7915.369985                    11.52
Children's Clothing   2.328292e+05   27178.099597                    11.67
Men's Golf Clubs      4.703580e+04    5517.989977                    11.73
Consumer Electronics  1.089913e+05   13223.399926                    12.13
Accessories           1.336715e+05   16643.520074                    12.45
Baby                  1.222956e+04    1525.029992                    12.47
CDs                   3.059590e+03     383.850000                    12.55
Music                 1.131221e+05   14436.319923                    12.76
Tennis & Racquet      4.458509e+04    5747.979996                    12.89
Garden                2.577687e+05   33443.010106                    12.97
Baseball & Softball   9.405715e+04   12762.130067                    13.57
Women's Clothing      1.402830e+05   19102.849930                    13.62
Soccer                2.647705e+04    3901.949953                    14.74
Toys                  6.104660e+03     900.710000                    14.75
Fitness Accessories   3.560144e+04    5258.390016                    14.77
Golf Bags & Carts     1.036939e+04    1810.069992                    17.46

The real business insight is:

High sales do not automatically translate into high profit margin. In this dataset, several of the largest categories generate substantial absolute profit, but their profit margin remains around 10–11%. Discount rates are also very similar across categories, so discounting does not explain the difference.

In [125]:
fishing_products = (
    df[df["Category Name"] == "Fishing"]
    .groupby("Product Name")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Order Profit Per Order", "sum"),
        Order_Items=("Order Item Id", "nunique")
    )
)

fishing_products["Profit_Margin_%"] = (
    fishing_products["Profit"] /
    fishing_products["Sales"] * 100
).round(2)

fishing_products.sort_values(
    "Sales",
    ascending=False
).head(15)

,Sales,Profit,Order_Items,Profit_Margin_%
Product Name,,,,
Field & Stream Sportsman 16 Gun Fire Safe,6.929654e+06,756220.76719,17325,10.91

In [126]:
product_profit = (
    df.dropna(subset=["Order Profit Per Order"])
      .groupby("Product Name")
      .agg(
          Total_Profit=("Order Profit Per Order", "sum"),
          Sales=("Sales", "sum"),
          Order_Items=("Order Item Id", "nunique")
      )
      .sort_values("Total_Profit", ascending=False)
)

product_profit.head(10)

,Total_Profit,Sales,Order_Items
Product Name,,,
Field & Stream Sportsman 16 Gun Fire Safe,756220.767190,6.929654e+06,17325
Perfect Fitness Perfect Rip Deck,493828.299782,4.421143e+06,24515
Diamondback Women's Serene Classic Comfort Bi,427455.568106,4.118426e+06,13729
Nike Men's Free 5.0+ Running Shoe,379915.818503,3.667633e+06,12169
Nike Men's Dri-FIT Victory Golf Polo,350421.029567,3.147800e+06,21035
Pelican Sunstream 100 Kayak,324076.370020,3.099845e+06,15500
O'Brien Men's Neoprene Life Vest,318451.430554,2.888994e+06,19298
Nike Men's CJ Elite 2 TD Football Cleat,311902.820214,2.891758e+06,22246
Under Armour Girls' Toddler Spine Surge Runni,126278.510299,1.269083e+06,10617
Dell Laptop,69656.810171,6.630000e+05,442

In [127]:
product_profit["Avg_Profit_Per_Item"] = (
    product_profit["Total_Profit"] /
    product_profit["Order_Items"]
).round(2)

product_profit.sort_values(
    "Avg_Profit_Per_Item",
    ascending=False
).head(10)

,Total_Profit,Sales,Order_Items,Avg_Profit_Per_Item
Product Name,,,,
Dell Laptop,69656.810171,6.630000e+05,442,157.59
Bowflex SelectTech 1090 Dumbbells,1190.779995,5.999900e+03,10,119.08
Lawn mower,33443.010106,2.577687e+05,484,69.10
Diamondback Boys' Insight 24 Performance Hybr,1730.809998,8.699710e+03,29,59.68
Polar FT4 Heart Rate Monitor,3476.849972,1.763804e+04,60,57.95
Porcelain crafts,25531.170060,2.233563e+05,484,52.75
Web Camera,30289.799946,2.676077e+05,592,51.17
The North Face Women's Recon Backpack,2803.799964,1.791900e+04,57,49.19
Elevation Training Mask 2.0,3299.569980,1.847769e+04,74,44.59
Field & Stream Sportsman 16 Gun Fire Safe,756220.767190,6.929654e+06,17325,43.65

In [128]:
product_category_counts = (
    df.groupby("Product Name")["Category Name"]
      .nunique()
      .sort_values(ascending=False)
)

product_category_counts.head(20)

Product Name
Adult dog supplies                               1
Baby sweater                                     1
Bag Boy Beverage Holder                          1
Bag Boy M330 Push Cart                           1
Bowflex SelectTech 1090 Dumbbells                1
Bridgestone e6 Straight Distance NFL Carolina    1
Bridgestone e6 Straight Distance NFL San Dieg    1
Bridgestone e6 Straight Distance NFL Tennesse    1
Brooks Women's Ghost 6 Running Shoe              1
Bushnell Pro X7 Jolt Slope Rangefinder           1
CDs of rock                                      1
Children's heaters                               1
Cleveland Golf Collegiate My Custom Wedge 588    1
Cleveland Golf Women's 588 RTX CB Satin Chrom    1
Clicgear 8.0 Shoe Brush                          1
Clicgear Rovic Cooler Bag                        1
Columbia Men's PFG Anchor Tough T-Shirt          1
DVDs                                             1
Dell Laptop                                      1
Diamondback Boys' Insight 24 Performance Hybr    1
Name: Category Name, dtype: int64

In [129]:
product_category_counts[product_category_counts > 1]

Series([], Name: Category Name, dtype: int64)

Our conclusion is:

Each product is consistently assigned to one category in the dataset, so there is no evidence of products being mapped to multiple categories.

In [130]:
category_sales = (
    df.groupby("Category Name")
      .agg(
          Total_Sales=("Sales", "sum"),
          Order_Items=("Order Item Id", "nunique")
      )
      .sort_values("Total_Sales", ascending=False)
)

category_sales.head(10)

                       Total_Sales  Order_Items
Category Name
Fishing               6.929654e+06        17325
Cleats                4.431943e+06        24551
Camping & Hiking      4.118426e+06        13729
Cardio Equipment      3.694843e+06        12487
Women's Apparel       3.147800e+06        21035
Water Sports          3.113845e+06        15540
Men's Footwear        2.891758e+06        22246
Indoor/Outdoor Games  2.888994e+06        19298
Shop By Sport         1.309522e+06        10984
Computers             6.630000e+05          442

In [131]:
customer_sales = (
    df.groupby("Customer Id")
      .agg(
          Total_Sales=("Sales", "sum"),
          Orders=("Order Id", "nunique")
      )
      .sort_values("Total_Sales", ascending=False)
)

customer_sales.head(10)

              Total_Sales  Orders
Customer Id
791          10524.170178      13
9371          9299.030207      11
8766          9296.140186      11
1657          9223.710152      11
2641          9130.920224      11
1288          9019.110199      12
3710          9019.100208      14
4249          8918.850134      13
5654          8904.950211      15
5624          8761.980183      12

In [132]:
top_10_customer_sales = customer_sales.head(10)["Total_Sales"].sum()

total_customer_sales = customer_sales["Total_Sales"].sum()

top_10_share = (
    top_10_customer_sales /
    total_customer_sales *
    100
)

top_10_share

np.float64(0.2503700566215058)

That means:

The top 10 customers account for approximately 25.04% of total sales.

In [133]:
customer_sales_sorted = customer_sales.sort_values(
    "Total_Sales",
    ascending=False
)

total_sales = customer_sales_sorted["Total_Sales"].sum()
total_customers = len(customer_sales_sorted)

for percentage in [1, 5, 10]:
    n = int(total_customers * percentage / 100)
    
    sales_share = (
        customer_sales_sorted.head(n)["Total_Sales"].sum()
        / total_sales
        * 100
    )
    
    print(f"Top {percentage}% of customers: {sales_share:.2f}% of sales")

Top 1% of customers: 4.04% of sales
Top 5% of customers: 16.47% of sales
Top 10% of customers: 29.19% of sales

In [134]:
#How many order items do the top customers actually have?
top_customers = customer_sales.head(10).index

df[df["Customer Id"].isin(top_customers)].groupby("Customer Id").agg(
    Order_Items=("Order Item Id", "nunique"),
    Orders=("Order Id", "nunique"),
    Sales=("Sales", "sum")
).sort_values("Sales", ascending=False)

             Order_Items  Orders         Sales
Customer Id
791                   43      13  10524.170178
9371                  44      11   9299.030207
8766                  38      11   9296.140186
1657                  42      11   9223.710152
2641                  43      11   9130.920224
1288                  42      12   9019.110199
3710                  42      14   9019.100208
4249                  39      13   8918.850134
5654                  47      15   8904.950211
5624                  38      12   8761.980183

In [135]:
df.groupby("Customer Id")["Sales"].sum()

Customer Id
1         499.950012
2        1819.730034
3        3537.680094
4        1719.630030
5        1274.750023
            ...
20753     215.820007
20754     215.820007
20755     327.750000
20756      11.540000
20757      39.750000
Name: Sales, Length: 20652, dtype: float64

In [136]:
top_10_sales = customer_sales.head(10)["Total_Sales"].sum()
total_sales = customer_sales["Total_Sales"].sum()

print("Top 10 sales:", top_10_sales)
print("Total sales:", total_sales)
print("Top 10 share:", (top_10_sales / total_sales) * 100)

Top 10 sales: 92097.96188106999
Total sales: 36784735.01337984
Top 10 share: 0.2503700566215058

A useful finding is:

Sales are broadly distributed across the customer base. The top 10 customers account for only 0.25% of total sales, while the top 10% of customers account for 29.19%.

In [137]:
#How does order size affect sales and profitability?

items_per_order = (
    df.groupby("Order Id")["Order Item Id"]
      .nunique()
)

items_per_order.describe()

count    65752.000000
mean         2.745453
std          1.478363
min          1.000000
25%          1.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: Order Item Id, dtype: float64

In [138]:
items_per_order.value_counts().sort_index()

Order Item Id
1    19850
2    11447
3    11398
4    11704
5    11353
Name: count, dtype: int64

In [139]:
order_value = (
    df.groupby("Order Id")
      .agg(
          Items=("Order Item Id", "nunique"),
          Sales=("Sales", "sum"),
          Profit=("Order Profit Per Order", "sum")
      )
)

order_value.head()

          Items        Sales      Profit
Order Id
1             1   299.980011   88.790001
2             3   579.980011  195.900002
4             4   699.850010  124.090000
5             5  1129.860039  390.089995
7             3   579.920013  203.929998

In [140]:
order_size_analysis = (
    order_value.groupby("Items")
    .agg(
        Orders=("Sales", "count"),
        Avg_Sales=("Sales", "mean"),
        Avg_Profit=("Profit", "mean")
    )
    .round(2)
)

order_size_analysis

       Orders  Avg_Sales  Avg_Profit
Items
1       19850     240.46       27.46
2       11447     399.88       42.25
3       11398     595.94       62.69
4       11704     795.55       86.77
5       11353     998.01      106.41

In [141]:
order_size_analysis["Profit_Per_Item"] = (
    order_size_analysis["Avg_Profit"]
    / order_size_analysis.index
).round(2)

order_size_analysis

       Orders  Avg_Sales  Avg_Profit  Profit_Per_Item
Items
1       19850     240.46       27.46            27.46
2       11447     399.88       42.25            21.12
3       11398     595.94       62.69            20.90
4       11704     795.55       86.77            21.69
5       11353     998.01      106.41            21.28

Business conclusion

Larger orders generate higher sales and total profit because they contain more items, while profit per item remains relatively stable for 2–5 item orders.

In [142]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect("../SQL/dataco_supply_chain.db")

# Load CSV
df = pd.read_csv(
    "../Data/raw/DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

# Upload dataframe to SQLite
df.to_sql(
    "supply_chain",
    conn,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

In [143]:
query = """
SELECT COUNT(*) AS total_rows
FROM supply_chain;
"""

pd.read_sql_query(query, conn)

   total_rows
0      180519

In [144]:
query = """
PRAGMA table_info(supply_chain);
"""

columns = pd.read_sql_query(query, conn)
columns

    cid                           name     type  notnull dflt_value  pk
0     0                           Type     TEXT        0       None   0
1     1       Days for shipping (real)  INTEGER        0       None   0
2     2  Days for shipment (scheduled)  INTEGER        0       None   0
3     3              Benefit per order     REAL        0       None   0
4     4             Sales per customer     REAL        0       None   0
5     5                Delivery Status     TEXT        0       None   0
6     6             Late_delivery_risk  INTEGER        0       None   0
7     7                    Category Id  INTEGER        0       None   0
8     8                  Category Name     TEXT        0       None   0
9     9                  Customer City     TEXT        0       None   0
10   10               Customer Country     TEXT        0       None   0
11   11                 Customer Email     TEXT        0       None   0
12   12                 Customer Fname     TEXT        0       None   0
13   13                    Customer Id  INTEGER        0       None   0
14   14                 Customer Lname     TEXT        0       None   0
15   15              Customer Password     TEXT        0       None   0
16   16               Customer Segment     TEXT        0       None   0
17   17                 Customer State     TEXT        0       None   0
18   18                Customer Street     TEXT        0       None   0
19   19               Customer Zipcode     REAL        0       None   0
20   20                  Department Id  INTEGER        0       None   0
21   21                Department Name     TEXT        0       None   0
22   22                       Latitude     REAL        0       None   0
23   23                      Longitude     REAL        0       None   0
24   24                         Market     TEXT        0       None   0
25   25                     Order City     TEXT        0       None   0
26   26                  Order Country     TEXT        0       None   0
27   27              Order Customer Id  INTEGER        0       None   0
28   28        order date (DateOrders)     TEXT        0       None   0
29   29                       Order Id  INTEGER        0       None   0
30   30         Order Item Cardprod Id  INTEGER        0       None   0
31   31            Order Item Discount     REAL        0       None   0
32   32       Order Item Discount Rate     REAL        0       None   0
33   33                  Order Item Id  INTEGER        0       None   0
34   34       Order Item Product Price     REAL        0       None   0
35   35        Order Item Profit Ratio     REAL        0       None   0
36   36            Order Item Quantity  INTEGER        0       None   0
37   37                          Sales     REAL        0       None   0
38   38               Order Item Total     REAL        0       None   0
39   39         Order Profit Per Order     REAL        0       None   0
40   40                   Order Region     TEXT        0       None   0
41   41                    Order State     TEXT        0       None   0
42   42                   Order Status     TEXT        0       None   0
43   43                  Order Zipcode     REAL        0       None   0
44   44                Product Card Id  INTEGER        0       None   0
45   45            Product Category Id  INTEGER        0       None   0
46   46            Product Description     REAL        0       None   0
47   47                  Product Image     TEXT        0       None   0
48   48                   Product Name     TEXT        0       None   0
49   49                  Product Price     REAL        0       None   0
50   50                 Product Status  INTEGER        0       None   0
51   51     shipping date (DateOrders)     TEXT        0       None   0
52   52                  Shipping Mode     TEXT        0       None   0